package com.cying.ideatools.codemaker.crud.ui;

import com.intellij.ide.util.MethodOrFunctionalExpressionCellRenderer;
import com.intellij.psi.PsiMethod;
import com.intellij.psi.util.PsiFormatUtilBase;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * @author chengying13378 chengying13378@hundsun.com
 * @ClassName SelectMethodUI
 * @Description TODO
 * @date 2019-01-29 21:10
 */
public class SelectMethodUI {

    private JPanel mypanel;
    private JList methodList;
    private JScrollPane myScrollPane;

    public static void main(String[] args) {
        JFrame frame = new JFrame("ParamFileEditorUi");
        frame.setContentPane(new SelectMethodUI().mypanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public SelectMethodUI() {

    }

    public SelectMethodUI(PsiMethod[] methods) {
        methodList.setListData(methods);
        methodList.setCellRenderer(new MethodOrFunctionalExpressionCellRenderer(true,
                PsiFormatUtilBase.SHOW_MODIFIERS
                        | PsiFormatUtilBase.SHOW_NAME
                        | PsiFormatUtilBase.SHOW_PARAMETERS
                        | PsiFormatUtilBase.SHOW_RAW_TYPE
                        | PsiFormatUtilBase.SHOW_THROWS));
        methodList.getSelectionModel().setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }


    public JList getMyList() {
        return methodList;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mypanel = new JPanel();
        mypanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        myScrollPane = new JScrollPane();
        mypanel.add(myScrollPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        methodList = new JList();
        myScrollPane.setViewportView(methodList);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mypanel;
    }

}
