package com.cying.ideatools.codemaker.crud.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * @author chengying13378 chengying13378@hundsun.com
 * @ClassName ShowCodeBlockUI
 * @Description TODO
 * @date 2019-01-30 13:58
 */
public class ShowCodeBlockUI {
    private JPanel mypanel;
    private JTextPane myTextPane;

    public static void main(String[] args) {
        JFrame frame = new JFrame("ParamFileEditorUi");
        frame.setContentPane(new ShowCodeBlockUI().mypanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public ShowCodeBlockUI() {
    }

    public ShowCodeBlockUI(String content) {
        myTextPane.setText(content);
    }

    public String getText() {
        return myTextPane.getText();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mypanel = new JPanel();
        mypanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        myTextPane = new JTextPane();
        mypanel.add(myTextPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mypanel;
    }

}
